# Generated by Django 5.1 on 2024-09-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts_ecommerce', '0001_initial'),
        ('customers_ecommerce', '0001_initial'),
        ('products_ecommerce', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customers_ecommerce.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products_ecommerce.product'),
        ),
    ]
