# Generated by Django 5.1 on 2024-09-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alpha2_code', models.CharField(max_length=2, unique=True)),
                ('alpha3_code', models.CharField(max_length=3, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('borders', models.JSONField(blank=True, null=True)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('flag', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
