# Generated by Django 5.1 on 2024-08-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
