# Generated by Django 5.1 on 2024-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0014_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='number_of_logins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
