# Generated by Django 5.1 on 2024-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
