# Generated by Django 5.1 on 2024-09-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_ecommerce', '0002_order_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, default='e7b7c3b0e275458b87762287105c6f5b', max_length=32),
        ),
    ]
