# Generated by Django 5.1 on 2024-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_ecommerce', '0003_alter_order_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, default='1b725379a9b5421ab38f8d9a85df9961', max_length=32, null=True),
        ),
    ]
