# Generated by Django 5.1 on 2024-09-01 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders_ecommerce', '0004_alter_order_confirmation_number'),
    ]
    
    def generate_unique_confirmation_numbers(apps, schema_editor):
        Order = apps.get_model('orders_ecommerce', 'Order')
        for order in Order.objects.all():
            if not order.confirmation_number:
                order.confirmation_number = uuid.uuid4().hex
                order.save()

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(generate_unique_confirmation_numbers),
    ]
