# Generated by Django 5.1 on 2024-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_ecommerce', '0005_alter_order_confirmation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
